### ISSUE TITLE
Project Missing Files

### ISSUE THREAD

**Issue by raffdp** [Samson-Mano/Quaternion_Arcball_3D_Rotation#1]
![image](https://user-images.githubusercontent.com/1573230/150360448-84d46888-72c9-47da-bddf-df94a5283388.png)

**Comment by Samson-Mano** [comment]
![image](https://user-images.githubusercontent.com/60636238/150404877-a9d8bb77-1702-4af1-b749-81d1da37cca5.png)
Uploaded Program & threeD_rotation.cs

**Comment by Samson-Mano** [comment]
![image](https://user-images.githubusercontent.com/60636238/150405130-26a5be74-c122-4add-928d-387fd7e078d8.png)
